name: Build and test oast

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install GCC
        uses: egor-tensin/setup-gcc@v1

      - name: Building
        run: make

      - name: Testing
        run: make test
